### ISSUE TITLE
Move UmbraSlice and UmbraString into a separate crate?

### ISSUE THREAD

**Issue by LennyLizowzskiy** [helix-editor/spellbook#3]
I've just finished reading the blog post about German strings in Spellbook, but the implementation is inbuilt into this larger crate. I understand that reimplementing them from scratch or just copying the code from here directly is easy, but it would be great if we could work on Umbra* in one place but without all the extra stuff coming from this crate

**Comment by the-mikedavis** [comment]
For sure! I copied over the code to https://github.com/the-mikedavis/umbra_slice and published a v0.1.0 version to crates: https://crates.io/crates/umbra_slice. I will keep the existing code here in Spellbook since it's small and probably won't change much.
